using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IotDashboard.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddCustomerTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'Customers' AND n.nspname = 'public'
    ) THEN
        CREATE TABLE ""Customers"" (
            ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" text NOT NULL,
            ""Slug"" text NOT NULL,
            ""Logo"" text NOT NULL,
            ""Description"" text NOT NULL,
            ""Email"" text NOT NULL,
            ""SubscriptionActive"" boolean NOT NULL,
            ""Status"" text NOT NULL,
            ""CreatedBy"" bigint NOT NULL,
            ""ModifiedBy"" bigint NULL,
            ""CreatedOn"" timestamp with time zone NOT NULL,
            ""ModifiedOn"" timestamp with time zone NULL,
            ""IsActive"" boolean NOT NULL,
            CONSTRAINT ""PK_Customers"" PRIMARY KEY (""Id"")
        );
    END IF;
END $$;");

            migrationBuilder.Sql(@"
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Customers_Slug""
ON ""Customers"" (""Slug"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP INDEX IF EXISTS ""IX_Customers_Slug"";
DROP TABLE IF EXISTS ""Customers"";");
        }
    }
}
