// <auto-generated />
using System;
using System.Collections.Generic;
using IotDashboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IotDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260704133633_AddUniqueUserNameIndex")]
    partial class AddUniqueUserNameIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IotDashboard.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SubscriptionActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AiEhsInstalled")
                        .HasColumnType("boolean");

                    b.Property<bool>("AiSecurityInstalled")
                        .HasColumnType("boolean");

                    b.Property<string>("AiSubscribeTopic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BatteryBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BatteryCapacity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("BatteryQty")
                        .HasColumnType("integer");

                    b.Property<int>("CamerasInstalledCount")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("GeneratorBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GeneratorCapacity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GeneratorQty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("KeepAliveSeconds")
                        .HasColumnType("integer");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MqttClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MqttHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MqttPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MqttPort")
                        .HasColumnType("integer");

                    b.Property<string>("MqttUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PublishTopic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RectifierBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RectifierCapacity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RectifierQty")
                        .HasColumnType("integer");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<string>("RmsSerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RmsSubscribeTopic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SimCardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SolarBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SolarCapacity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SolarQty")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SubRegionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("UseTls")
                        .HasColumnType("boolean");

                    b.Property<long>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("SubRegionId");

                    b.HasIndex("ZoneId");

                    b.HasIndex("CustomerId", "Code")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.DeviceTelemetryLatest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DecodeError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsCrcValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SummaryPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceTelemetryLatest", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("CustomerId", "Code")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Lookup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Lookups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "LocationType",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Region",
                            Order = 1,
                            Value = "1"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "LocationType",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "SubRegion",
                            Order = 2,
                            Value = "2"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "LocationType",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Zone",
                            Order = 3,
                            Value = "3"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Status",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Active",
                            Order = 1,
                            Value = "Active"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Status",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Inactive",
                            Order = 2,
                            Value = "Inactive"
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Status",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Suspended",
                            Order = 3,
                            Value = "Suspended"
                        },
                        new
                        {
                            Id = 7L,
                            Category = "SubscriptionStatus",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Active",
                            Order = 1,
                            Value = "Active"
                        },
                        new
                        {
                            Id = 8L,
                            Category = "SubscriptionStatus",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Inactive",
                            Order = 2,
                            Value = "Inactive"
                        },
                        new
                        {
                            Id = 9L,
                            Category = "SubscriptionStatus",
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Expired",
                            Order = 3,
                            Value = "Expired"
                        });
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.TelecomTelemetryPacket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AcFrequency")
                        .HasColumnType("numeric");

                    b.Property<byte?>("ActiveAlarmCount")
                        .HasColumnType("smallint");

                    b.Property<int?>("Alarm1Code")
                        .HasColumnType("integer");

                    b.Property<byte?>("Alarm1Level")
                        .HasColumnType("smallint");

                    b.Property<int?>("Alarm2Code")
                        .HasColumnType("integer");

                    b.Property<byte?>("Alarm2Level")
                        .HasColumnType("smallint");

                    b.Property<int?>("Alarm3Code")
                        .HasColumnType("integer");

                    b.Property<byte?>("Alarm3Level")
                        .HasColumnType("smallint");

                    b.Property<long?>("AlarmBitmap1")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("AmbientTemperature1")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AmbientTemperature2")
                        .HasColumnType("numeric");

                    b.Property<int?>("BatteryBackupTimeMin")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BatteryChargeDischargeKw")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BatteryCurrent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BatteryRemainingCapacityAh")
                        .HasColumnType("numeric");

                    b.Property<byte?>("BatteryRemainingPercent")
                        .HasColumnType("smallint");

                    b.Property<byte?>("BatterySoh")
                        .HasColumnType("smallint");

                    b.Property<byte?>("BatteryStatus")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("BatteryTemperature")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BatteryTotalCapacityAh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BatteryVoltage")
                        .HasColumnType("numeric");

                    b.Property<byte?>("BmuOnlineCount")
                        .HasColumnType("smallint");

                    b.Property<int?>("Crc16")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DcBusVoltage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DcLoadCurrent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DcLoadPercent")
                        .HasColumnType("numeric");

                    b.Property<long?>("DcLoadPowerW")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("DeviceIdHash")
                        .HasColumnType("bigint");

                    b.Property<int>("DeviceNumber")
                        .HasColumnType("integer");

                    b.Property<byte?>("DeviceType")
                        .HasColumnType("smallint");

                    b.Property<int?>("DigitalInputBitmap")
                        .HasColumnType("integer");

                    b.Property<bool?>("DoorOpenAlarm")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EpochTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<byte?>("FuelLevelPercent")
                        .HasColumnType("smallint");

                    b.Property<bool?>("FuelLowAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool?>("FuelTheftAlarm")
                        .HasColumnType("boolean");

                    b.Property<int?>("FuelVolumeL")
                        .HasColumnType("integer");

                    b.Property<bool?>("GensetAvailable")
                        .HasColumnType("boolean");

                    b.Property<byte?>("GensetControlMode")
                        .HasColumnType("smallint");

                    b.Property<int?>("GensetRunHours")
                        .HasColumnType("integer");

                    b.Property<bool?>("GensetRunning")
                        .HasColumnType("boolean");

                    b.Property<int?>("GensetStartCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("GensetStartFailure")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsCrcValid")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LineACurrent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LineAVoltage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LineBCurrent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LineBVoltage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LineCCurrent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LineCVoltage")
                        .HasColumnType("numeric");

                    b.Property<bool?>("MainsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MainsFailure")
                        .HasColumnType("boolean");

                    b.Property<byte?>("Manufacturer")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Model")
                        .HasColumnType("smallint");

                    b.Property<bool?>("MotionAlarm")
                        .HasColumnType("boolean");

                    b.Property<int?>("PacketSequence")
                        .HasColumnType("integer");

                    b.Property<byte?>("PacketVersion")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("PortalReceiveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("RectifierAcFail")
                        .HasColumnType("boolean");

                    b.Property<byte?>("RectifierCommCount")
                        .HasColumnType("smallint");

                    b.Property<byte?>("RectifierInstalledCount")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("RectifierMaxTemperature")
                        .HasColumnType("numeric");

                    b.Property<bool?>("RectifierMissing")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("RectifierTotalCurrent")
                        .HasColumnType("numeric");

                    b.Property<long?>("RectifierTotalDcPowerW")
                        .HasColumnType("bigint");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("RelayOutputBitmap")
                        .HasColumnType("integer");

                    b.Property<int>("SiteNumber")
                        .HasColumnType("integer");

                    b.Property<bool?>("SmokeAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SolarAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("SolarChargingHours")
                        .HasColumnType("integer");

                    b.Property<byte?>("SolarControllerCommFail")
                        .HasColumnType("smallint");

                    b.Property<byte?>("SolarControllerCount")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("SolarCurrent")
                        .HasColumnType("numeric");

                    b.Property<long?>("SolarEnergyTodayWh")
                        .HasColumnType("bigint");

                    b.Property<long?>("SolarPowerW")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SolarVoltage")
                        .HasColumnType("numeric");

                    b.Property<long>("SubRegionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SystemStatus")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantNumber")
                        .HasColumnType("integer");

                    b.Property<long?>("TotalAcEnergyWh")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalAcInputPowerW")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalDcEnergyWh")
                        .HasColumnType("bigint");

                    b.Property<bool?>("WaterLeakAlarm")
                        .HasColumnType("boolean");

                    b.Property<long>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TelecomTelemetryPackets");
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.TelemetryMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DecodeError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DecodedPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsCrcValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("TenantId", "DeviceId", "ReceivedAtUtc");

                    b.ToTable("TelemetryMessages", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Code")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<long>>("Modules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint[]")
                        .HasDefaultValueSql("'{}'::bigint[]");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.UserToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiredDateTimeUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TokenTries")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Weather", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ProviderKey", "LoginProvider");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Device", b =>
                {
                    b.HasOne("IotDashboard.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IotDashboard.Domain.Entities.Location", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IotDashboard.Domain.Entities.Location", "SubRegion")
                        .WithMany()
                        .HasForeignKey("SubRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IotDashboard.Domain.Entities.Location", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Region");

                    b.Navigation("SubRegion");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Location", b =>
                {
                    b.HasOne("IotDashboard.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IotDashboard.Domain.Entities.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("IotDashboard.Domain.Entities.Customer", "Customer")
                        .WithOne("Subscription")
                        .HasForeignKey("IotDashboard.Domain.Entities.Subscription", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("IotDashboard.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.User", b =>
                {
                    b.HasOne("IotDashboard.Domain.Entities.Customer", "Customer")
                        .WithMany("Users")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("IotDashboard.Domain.Entities.User", null)
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Subscription");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.Location", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("IotDashboard.Domain.Entities.User", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
